stages:
  - build
  - test_style
  - integration_test
  - deploy

build-cat:
  stage: build
  script:
    - cd src/project/cat/ && make build
    - bash ../../telegram.sh $?
  artifacts:
    paths: 
      - src/project/cat/s21_cat
    expire_in: 30 days

build-grep:
  stage: build
  script:
    - cd src/project/grep/ && make build
    - bash ../../telegram.sh $?
  artifacts:
    paths:
      - src/project/grep/s21_grep
    expire_in: 30 days

style-cat:
  stage: test_style
  needs: ["build-cat"]
  script: 
    - cd src/project/cat/ && clang-format -n -Werror *.c; bash ../../telegram.sh $?
  when: on_success

style-grep:
  stage: test_style
  needs: ["build-grep"]
  script: 
    - cd src/project/grep/ && clang-format -n -Werror *.c; bash ../../telegram.sh $?
  when: on_success

test-cat:
  stage: integration_test
  needs: ["build-cat", "style-cat"]
  script: 
    - cd src/project/cat/ && make test; bash ../../telegram.sh $?
  when: on_success

test-grep:
  stage: integration_test
  needs: ["build-grep", "style-grep"]
  script: 
    - cd src/project/grep/ && make test; bash ../../telegram.sh $?
  when: on_success

deploy:
  stage: deploy
  needs: ["build-cat", "build-grep", "style-cat", "style-grep", "test-cat", "test-grep"]
  script: 
    - cd src && bash deploy.sh
    - bash telegram.sh $?
  when: on_success
