build-job1:
  stage: build
  script:
    - cd src/project/cat/ && make build

build-job2:
  stage: build
  script:
    - cd src/project/grep/ && make build

test-job1:
  stage: test
  script: 
    - cd src/project/cat/ && make test

test-job2:
  stage: test
  script: 
    - cd src/project/grep/ && make test