build-cat:
  stage: build
  script:
    - cd src/project/cat/ && make build
  artifacts:
    name: "cat_build"
    paths: 
      - src/project/cat/s21_cat
    expire_in: 30 days

build-grep:
  stage: build
  script:
    - cd src/project/grep/ && make build
  artifacts:
    name: "grep_build"
    paths: 
      - src/project/cat/s21_grep
    expire_in: 30 days

style-cat:
  stage: test
  script: 
    - cd src/project/cat/ && clang-format -n *.c
  workflow:
      fail_fast: true

style-grep:
  stage: test
  script: 
    - cd src/project/grep/ && clang-format -n *.c
  workflow:
      fail_fast: true

test-cat:
  stage: test
  script: 
    - cd src/project/cat/ && make test
  workflow:
      fail_fast: true

test-grep:
  stage: test
  script: 
    - cd src/project/grep/ && make test
  workflow:
      fail_fast: true
