stages:
  - build
  - test_style
  - integration_test
  - deploy


build:
  stage: build
  script:
    - cd src/project/cat/ && make build
    - cd ../grep/ && make build
  artifacts:
    # name: "cat_build"
    paths: 
      - src/project/cat/s21_cat
      - src/project/cat/s21_grep
    expire_in: 30 days

# build-grep:
#   stage: build
#   script:
#     - cd src/project/grep/ && make build
#   artifacts:
#     name: "grep_build"
#     paths: 
#       - src/project/cat/s21_grep
#     expire_in: 30 days


style-cat:
  stage: test_style
  needs: ["build"]
  script: 
    - cd src/project/cat/ && clang-format -n -Werror *.c
  # allow_failure: false
  when: on_success

style-grep:
  stage: test_style
  needs: ["build"]
  script: 
    - cd src/project/grep/ && clang-format -n -Werror *.c
  # allow_failure: false
  when: on_success


test-cat:
  stage: integration_test
  needs: ["build", "style-cat", "style-grep"]
  script: 
    - cd src/project/cat/ && make test
  # allow_failure: false
  when: on_success

test-grep:
  stage: integration_test
  needs: ["build", "style-cat", "style-grep"]
  script: 
    - cd src/project/grep/ && make test
  # allow_failure: false
  when: on_success
