build-cat:
  stage: build
  script:
    - cd src/project/cat/ && make build
    - mkdir -p binaries/cat/ && cp s21_cat binaries/cat/
  artifacts:
    name: "cat_build"
    paths: 
      - src/project/cat/binaries/cat/
    expire_in: 30 days

build-grep:
  stage: build
  script:
    - cd src/project/grep/ && make build
  artifacts:
    name: "grep_build"
    paths: 
      - binaries/grep/
    expire_in: 30 days

style-cat:
  stage: test
  script: 
    - cd src/project/cat/ && clang-format -n *.c

style-grep:
  stage: test
  script: 
    - cd src/project/grep/ && clang-format -n *.c

test-cat:
  stage: test
  script: 
    - cd src/project/cat/ && make test

test-grep:
  stage: test
  script: 
    - cd src/project/grep/ && make test
