build-cat:
  stage: build
  script:
    - cd src/project/cat/ && make build
  artifacts:
    name: "cat_build"
    paths: 
      - src/project/cat/s21_cat
    expire_in: 30 days

build-grep:
  stage: build
  script:
    - cd src/project/grep/ && make build
  artifacts:
    name: "grep_build"
    paths: 
      - src/project/cat/s21_grep
    expire_in: 30 days

style-cat:
  stage: test
  script: 
    - cd src/project/cat/ && make lint

style-grep:
  stage: test
  when: on_success
  script: 
    - cd src/project/grep/ && clang-format -n *.c

test-cat:
  stage: test
  when: on_success
  script: 
    - cd src/project/cat/ && make test

test-grep:
  stage: test
  when: on_success
  script: 
    - cd src/project/grep/ && make test
