stages:
  - build
  - test_style
  - integration_test
  - deploy

build-cat:
  stage: build
  script:
    - cd src/project/cat/ && make build
  after_script:
    - bash src/telegram.sh $?
  artifacts:
    paths: 
      - src/project/cat/s21_cat
    expire_in: 30 days

build-grep:
  stage: build
  script:
    - cd src/project/grep/ && make build
  after_script:
    - bash src/telegram.sh $?
  artifacts:
    paths:
      - src/project/grep/s21_grep
    expire_in: 30 days

style-cat:
  stage: test_style
  needs: ["build-cat"]
  when: on_success
  script: 
    - cd src/project/cat/ && clang-format -n -Werror *.c
  after_script:
    - bash src/telegram.sh $?

style-grep:
  stage: test_style
  needs: ["build-grep"]
  when: on_success
  script: 
    - cd src/project/grep/ && clang-format -n -Werror *.c
  after_script:
    - bash src/telegram.sh $?

test-cat:
  stage: integration_test
  needs: ["build-cat", "style-cat"]
  when: on_success
  script: 
    - cd src/project/cat/ && make test
  after_script:
    - bash src/telegram.sh $?

test-grep:
  stage: integration_test
  needs: ["build-grep", "style-grep"]
  when: on_success
  script: 
    - cd src/project/grep/ && make test
  after_script:
    - bash src/telegram.sh $?

deploy:
  stage: deploy
  needs: ["build-cat", "build-grep", "style-cat", "style-grep", "test-cat", "test-grep"]
  when: on_success
  script: 
    - cd src && bash deploy.sh
  after_script:
    - bash telegram.sh $?
